// ----------------------------------------------------------------------
// Zero-Copy Direct Memory Read
// ----------------------------------------------------------------------
struct Node {
    pos_dim: vec4<f32>,       // [x, y, width, height]
    velocity_mass: vec4<f32>, // [vx, vy, mass, thermal_decay]
    uv_bounds: vec4<f32>      // [uMin, vMin, uMax, vMax]
}

@group(0) @binding(0) var<storage, read> nodes: array<Node>;

// ----------------------------------------------------------------------
// Camera Uniform (Pan & Zoom)
// ----------------------------------------------------------------------
struct Camera {
    offset: vec2<f32>,
    scale: vec2<f32>,
    resolution: vec2<f32>
}
@group(0) @binding(1) var<uniform> camera: Camera;

// ----------------------------------------------------------------------
// Edge Topology Buffer
// ----------------------------------------------------------------------
@group(0) @binding(2) var<storage, read> edges: array<vec2<u32>>;

// ----------------------------------------------------------------------
// Pretext Texture Atlas
// ----------------------------------------------------------------------
@group(0) @binding(3) var atlas: texture_2d<f32>;
@group(0) @binding(4) var atlas_sampler: sampler;

// ----------------------------------------------------------------------
// Vertex to Fragment Structure
// ----------------------------------------------------------------------
struct FragmentPayload {
    @builtin(position) position: vec4<f32>,
    @location(0) uv: vec2<f32>,
    @location(1) dimensions: vec2<f32>,
    @location(2) volatility: f32,
    @location(3) atlas_uv: vec2<f32>
}

// ----------------------------------------------------------------------
// Vertex Shader (Node Instancing)
// ----------------------------------------------------------------------
const QUAD_VERTICES = array<vec2<f32>, 6>(
    vec2<f32>(-0.5, -0.5), vec2<f32>( 0.5, -0.5), vec2<f32>( 0.5,  0.5),
    vec2<f32>(-0.5, -0.5), vec2<f32>( 0.5,  0.5), vec2<f32>(-0.5,  0.5)
);

@vertex
fn vs_main(
    @builtin(vertex_index) vertex_index: u32,
    @builtin(instance_index) instance_index: u32
) -> FragmentPayload {
    var out: FragmentPayload;
    
    // 1. Pull the node memory directly from the Compute layout
    let node = nodes[instance_index];
    
    // 2. Base primitive geometry
    let vertex = QUAD_VERTICES[vertex_index];
    var world_pos = vertex * node.pos_dim.zw + node.pos_dim.xy;
    
    // 3. Camera pan/zoom transformation
    world_pos = (world_pos + camera.offset) * camera.scale;

    // 4. Translate arbitrary physics space to NDC [-1.0, 1.0]
    // Assumes world_pos origin is top-left or derived against viewport res
    let ndc_x = (world_pos.x / camera.resolution.x) * 2.0 - 1.0;
    let ndc_y = (world_pos.y / camera.resolution.y) * 2.0 - 1.0;

    out.position = vec4<f32>(ndc_x, -ndc_y, 0.0, 1.0); // Negate Y for Canvas standard
    
    // 5. Build fragment mapping structure
    out.uv = vertex + 0.5; // [0.0 -> 1.0] bounds
    out.dimensions = node.pos_dim.zw;
    
    // UV map bounds generated by Phase 5 Pretext packer
    out.atlas_uv = vec2<f32>(
        mix(node.uv_bounds.x, node.uv_bounds.z, out.uv.x),
        mix(node.uv_bounds.y, node.uv_bounds.w, out.uv.y)
    );
    
    // Use velocity hypotenuse as a cheap proxy for "Volatility" (Churn)
    out.volatility = length(node.velocity_mass.xy) * 10.0;
    
    return out;
}

// ----------------------------------------------------------------------
// Fragment Shader (Glassmorphism + Thermodynamics)
// ----------------------------------------------------------------------
@fragment
fn fs_main(in: FragmentPayload) -> @location(0) vec4<f32> {
    
    // Color mapping: 
    // Stable = Deep Emerald (#10b981 -> 0.06, 0.72, 0.5)
    // Volatile = Glowing Red (#ef4444 -> 0.93, 0.26, 0.26)
    let emerald = vec3<f32>(0.06, 0.72, 0.5);
    let crimson = vec3<f32>(0.93, 0.26, 0.26);
    
    let base_color = mix(emerald, crimson, clamp(in.volatility, 0.0, 1.0));
    
    // Glassmorphism Smoothstep Border (Corner rounding)
    let d = length(in.uv - 0.5) * 2.0; 
    let block_alpha = 1.0 - smoothstep(0.9, 1.0, d);
    
    // Translucency mix for the node block
    var block_rgba = vec4<f32>(base_color, block_alpha * 0.85); 

    // Phase 5 Anti-Aliasing font injection
    let font_pixel = textureSample(atlas, atlas_sampler, in.atlas_uv);
    let font_white = vec3<f32>(1.0, 1.0, 1.0);
    
    // We mix using the sampled texture alpha (font_pixel.a) to perfectly preserve sub-pixel AA.
    let final_color = mix(block_rgba.rgb, font_white, font_pixel.a);
    let final_alpha = max(block_rgba.a, font_pixel.a); // Solidify text alpha over translucent node

    return vec4<f32>(final_color, final_alpha); 
}

// ----------------------------------------------------------------------
// Edge Render Shaders (NPMI Gravity Tethers)
// ----------------------------------------------------------------------
@vertex
fn vs_edge_main(@builtin(vertex_index) vertex_index: u32) -> @builtin(position) vec4<f32> {
    let edge_idx = vertex_index / 2u;
    let is_target = vertex_index % 2u;
    
    let edge = edges[edge_idx];
    let node_idx = select(edge.x, edge.y, is_target == 1u);
    let node = nodes[node_idx];
    
    var world_pos = node.pos_dim.xy;
    world_pos = (world_pos + camera.offset) * camera.scale;

    let ndc_x = (world_pos.x / camera.resolution.x) * 2.0 - 1.0;
    let ndc_y = (world_pos.y / camera.resolution.y) * 2.0 - 1.0;

    return vec4<f32>(ndc_x, -ndc_y, 0.0, 1.0);
}

@fragment
fn fs_edge_main() -> @location(0) vec4<f32> {
    // Dim tether baseline #333333 to contrast with brilliant Glassmorphism blocks.
    // In Phase 5, we will map Implicit Contracts here to glow brilliant white.
    return vec4<f32>(0.2, 0.2, 0.2, 0.5); 
}
