"""CO_CHANGE_ATLAS.md renderer.

Renders structural coupling patterns from git history: coupling clusters,
ghost couplings, stability zones, and hub files.
"""

import json
import os
import time
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

from .models import GenerateConfig, GeneratedArtifact


def render_atlas(
    root: str,
    config: GenerateConfig,
    timestamp: str,
    commit: str,
) -> GeneratedArtifact:
    """Render CO_CHANGE_ATLAS.md."""
    npmi_index = _load_npmi_index(root)
    file_histories = _load_file_histories(root)
    graph_hubs = _load_graph_hubs(root)
    graph_edges = _load_import_edges(root)
    network_edges = _load_network_edges(root)
    scope_index = _build_file_scope_index(root)

    lines = [f"# Co-Change Atlas\n"]
    lines.append(f"Generated by dotscope · {timestamp} · commit {commit}\n")

    stats = {"clusters": 0, "ghosts": 0, "volatile": 0, "stable": 0, "hubs": 0}

    # Coupling Clusters
    clusters = _build_coupling_clusters(npmi_index, scope_index)
    if clusters:
        lines.append("\n## Coupling Clusters\n")
        for cluster_name, pairs in sorted(clusters.items()):
            lines.append(f"\n### {cluster_name}\n")
            lines.append("| File A | File B | NPMI | Import Link? |")
            lines.append("|--------|--------|------|--------------|")
            pairs.sort(key=lambda p: (-p[2], p[0]))
            for fa, fb, npmi in pairs:
                has_import = _has_import_link(fa, fb, graph_edges, network_edges)
                link = "Yes" if has_import else "No"
                lines.append(f"| `{fa}` | `{fb}` | {npmi:.2f} | {link} |")
                stats["clusters"] += 1

    # Ghost Couplings
    ghosts = _find_ghost_couplings(
        npmi_index, graph_edges, network_edges, scope_index,
        threshold=config.ghost_coupling_threshold,
    )
    if ghosts:
        lines.append(f"\n## Ghost Couplings\n")
        lines.append(f"Files with NPMI > {config.ghost_coupling_threshold} and NO import or network relationship:\n")
        lines.append("| File A | File B | NPMI | Likely Reason |")
        lines.append("|--------|--------|------|---------------|")
        ghosts.sort(key=lambda g: (-g[2], g[0]))
        for fa, fb, npmi in ghosts:
            reason = _derive_ghost_reason(fa, fb, scope_index)
            lines.append(f"| `{fa}` | `{fb}` | {npmi:.2f} | {reason} |")
            stats["ghosts"] += 1

    # Stability Zones
    volatile, destabilized, stable = _classify_stability(
        file_histories, config.stability_window_days,
    )

    if volatile:
        lines.append("\n## Stability Zones\n")
        lines.append(f"\n### Volatile (changed frequently in last {config.stability_window_days} days)\n")
        volatile.sort(key=lambda v: (-v[1], v[0]))
        for path, commits in volatile:
            lines.append(f"- `{path}` — {commits} commits")
        stats["volatile"] = len(volatile)

    if destabilized:
        lines.append(f"\n### Recently Destabilized\n")
        destabilized.sort(key=lambda d: (-d[2], d[0]))
        for path, prev_stability, recent_commits in destabilized:
            lines.append(f"- `{path}` — was {prev_stability}, {recent_commits} commits recently")

    if stable:
        lines.append(f"\n### Stable (unchanged >{config.stability_window_days * 2} days)\n")
        stable.sort(key=lambda s: (s[1], s[0]))
        for path, last_mod in stable:
            date_str = time.strftime("%Y-%m-%d", time.localtime(last_mod)) if last_mod > 0 else "unknown"
            lines.append(f"- `{path}` — last modified {date_str}")
        stats["stable"] = len(stable)

    # Hub Files
    hubs = _find_hub_files(graph_hubs, config.hub_threshold_pct)
    if hubs:
        lines.append(f"\n## Hub Files\n")
        lines.append(f"Files imported by >{config.hub_threshold_pct}% of codebase modules:\n")
        lines.append("| File | Imported By | % of Modules |")
        lines.append("|------|-------------|--------------|")
        hubs.sort(key=lambda h: (-h[2], h[0]))
        for path, count, pct in hubs:
            lines.append(f"| `{path}` | {count} files | {pct:.0f}% |")
            stats["hubs"] += 1

    content = "\n".join(lines)

    return GeneratedArtifact(
        name="co_change_atlas",
        content=content,
        file_name="CO_CHANGE_ATLAS.md",
        data_sources=["npmi_index.json", "history.json", "graph_hubs.json"],
        stats=stats,
    )


# ---------------------------------------------------------------------------
# Analysis functions
# ---------------------------------------------------------------------------

def _build_coupling_clusters(
    npmi_index: Dict[str, Dict[str, float]],
    scope_index: Dict[str, str],
) -> Dict[str, List[Tuple[str, str, float]]]:
    """Group co-change pairs by scope pair."""
    clusters: Dict[str, List[Tuple[str, str, float]]] = {}
    seen = set()

    for fa, partners in sorted(npmi_index.items()):
        for fb, npmi in sorted(partners.items()):
            if npmi < 0.5:
                continue
            key = tuple(sorted([fa, fb]))
            if key in seen:
                continue
            seen.add(key)

            scope_a = scope_index.get(fa, os.path.dirname(fa).split("/")[0] or "root")
            scope_b = scope_index.get(fb, os.path.dirname(fb).split("/")[0] or "root")
            cluster_name = " <-> ".join(sorted([scope_a, scope_b]))

            if cluster_name not in clusters:
                clusters[cluster_name] = []
            clusters[cluster_name].append((key[0], key[1], npmi))

    return clusters


def _find_ghost_couplings(
    npmi_index: Dict[str, Dict[str, float]],
    graph_edges: Dict[str, List[str]],
    network_edges: Dict[str, Dict[str, list]],
    scope_index: Dict[str, str],
    threshold: float = 0.6,
) -> List[Tuple[str, str, float]]:
    """Find file pairs with high NPMI but no import or network link."""
    ghosts = []
    seen = set()

    for fa, partners in sorted(npmi_index.items()):
        for fb, npmi in sorted(partners.items()):
            if npmi < threshold:
                continue
            key = tuple(sorted([fa, fb]))
            if key in seen:
                continue
            seen.add(key)

            if _has_import_link(fa, fb, graph_edges, network_edges):
                continue

            ghosts.append((key[0], key[1], npmi))

    return ghosts


def _has_import_link(
    fa: str, fb: str,
    graph_edges: Dict[str, List[str]],
    network_edges: Dict[str, Dict[str, list]],
) -> bool:
    """Check if two files have an import or network relationship."""
    # Direct import
    if fb in graph_edges.get(fa, []) or fa in graph_edges.get(fb, []):
        return True
    # Network edge
    if fb in network_edges.get(fa, {}) or fa in network_edges.get(fb, {}):
        return True
    return False


def _derive_ghost_reason(
    fa: str, fb: str,
    scope_index: Dict[str, str],
) -> str:
    """Derive a heuristic reason for a ghost coupling."""
    scope_a = scope_index.get(fa, "")
    scope_b = scope_index.get(fb, "")

    if scope_a and scope_b and scope_a != scope_b:
        return f"{scope_a} logic depends on {scope_b} configuration"

    stem_a = os.path.splitext(os.path.basename(fa))[0]
    stem_b = os.path.splitext(os.path.basename(fb))[0]
    return f"{stem_a} and {stem_b} change together with no direct import"


def _classify_stability(
    file_histories: Dict[str, dict],
    window_days: int,
) -> Tuple[list, list, list]:
    """Classify files into volatile, destabilized, and stable."""
    now = time.time()
    window = window_days * 86400
    double_window = window_days * 2 * 86400

    volatile = []      # (path, commit_count)
    destabilized = []   # (path, prev_stability, recent_commits)
    stable = []         # (path, last_modified)

    for path, history in sorted(file_histories.items()):
        stability = history.get("stability", "")
        last_mod = history.get("last_modified", 0)
        commit_count = history.get("commit_count", 0)
        recent_commits = history.get("recent_commits", commit_count)

        age = now - last_mod if last_mod > 0 else double_window + 1

        if age < window and recent_commits > 5:
            volatile.append((path, recent_commits))
        elif stability == "stable" and age < window:
            destabilized.append((path, "stable", recent_commits))
        elif age > double_window:
            stable.append((path, last_mod))

    return volatile, destabilized, stable


def _find_hub_files(
    graph_hubs: Dict[str, dict],
    threshold_pct: int,
) -> List[Tuple[str, int, float]]:
    """Find files imported by > threshold_pct of modules."""
    if not graph_hubs:
        return []

    total_files = len(graph_hubs)
    if total_files == 0:
        return []

    hubs = []
    for path, hub in graph_hubs.items():
        count = hub.get("imported_by_count", 0)
        pct = (count / total_files) * 100
        if pct >= threshold_pct:
            hubs.append((path, count, pct))

    return hubs


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _load_npmi_index(root: str) -> Dict[str, Dict[str, float]]:
    path = Path(root) / ".dotscope" / "cache" / "npmi_index.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _load_file_histories(root: str) -> Dict[str, dict]:
    try:
        from ..storage.cache import load_cached_history
        history = load_cached_history(root)
        if not history:
            return {}
        result = {}
        for fh in getattr(history, "file_histories", {}).values():
            result[fh.path] = {
                "stability": getattr(fh, "stability", ""),
                "last_modified": getattr(fh, "last_modified", 0),
                "commit_count": getattr(fh, "commit_count", 0),
                "recent_commits": getattr(fh, "commit_count", 0),
            }
        return result
    except Exception:
        return {}


def _load_graph_hubs(root: str) -> Dict[str, dict]:
    try:
        from ..storage.cache import load_cached_graph_hubs
        return load_cached_graph_hubs(root)
    except Exception:
        return {}


def _load_import_edges(root: str) -> Dict[str, List[str]]:
    try:
        from ..storage.cache import load_cached_graph_hubs
        hubs = load_cached_graph_hubs(root)
        edges: Dict[str, List[str]] = {}
        for path, hub in hubs.items():
            imported_by = hub.get("imported_by_files", [])
            if isinstance(imported_by, list):
                for importer in imported_by:
                    if importer not in edges:
                        edges[importer] = []
                    edges[importer].append(path)
        return edges
    except Exception:
        return {}


def _load_network_edges(root: str) -> Dict[str, Dict[str, list]]:
    try:
        from ..storage.cache import load_cached_network_edges
        return load_cached_network_edges(root)
    except Exception:
        return {}


def _build_file_scope_index(root: str) -> Dict[str, str]:
    try:
        from ..discovery import find_all_scopes
        from ..parser import parse_scope_file
        index = {}
        for sf in find_all_scopes(root):
            try:
                config = parse_scope_file(sf)
                name = os.path.basename(os.path.dirname(config.path)) or "root"
                for inc in config.includes:
                    index[inc] = name
            except Exception:
                continue
        return index
    except Exception:
        return {}
