"""ARCHITECTURE_CONTRACTS.md renderer.

Renders implicit contracts, boundary contracts, anti-patterns, and
conventions per scope. Computes a scope-pair import matrix from
graph edges to detect boundary contracts (absent cross-scope imports).
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Optional

from .models import GenerateConfig, GeneratedArtifact


def render_contracts(
    root: str,
    config: GenerateConfig,
    timestamp: str,
    commit: str,
) -> GeneratedArtifact:
    """Render ARCHITECTURE_CONTRACTS.md."""
    scopes = _load_scope_data(root)
    graph_edges = _load_graph_edges(root)
    npmi_index = _load_npmi_index(root)

    lines = [f"# Architecture Contracts\n"]
    lines.append(f"Generated by dotscope · {timestamp} · commit {commit}\n")

    stats = {"scopes": 0, "contracts": 0, "anti_patterns": 0, "conventions": 0}

    # Compute scope-pair import matrix for boundary detection
    scope_imports = _compute_scope_import_matrix(scopes, graph_edges)

    for scope_name in sorted(scopes.keys()):
        scope = scopes[scope_name]
        sections = []

        # Co-change contracts from NPMI
        cochange = _render_cochange(scope_name, scope, npmi_index)
        if cochange:
            sections.append(cochange)
            stats["contracts"] += cochange.count("\n- ")

        # Boundary contracts
        boundaries = _render_boundaries(scope_name, scopes, scope_imports)
        if boundaries:
            sections.append(boundaries)

        # Anti-patterns
        anti = _render_anti_patterns(scope)
        if anti:
            sections.append(anti)
            stats["anti_patterns"] += anti.count("\n- ")

        # Conventions
        convs = _render_conventions(scope)
        if convs:
            sections.append(convs)
            stats["conventions"] += convs.count("\n- ")

        if sections or config.include_empty_scopes:
            stats["scopes"] += 1
            lines.append(f"\n## {scope_name}\n")
            lines.extend(sections)

    content = "\n".join(lines)

    return GeneratedArtifact(
        name="architecture_contracts",
        content=content,
        file_name="ARCHITECTURE_CONTRACTS.md",
        data_sources=["scope files", "graph.json", "npmi_index.json"],
        stats=stats,
    )


# ---------------------------------------------------------------------------
# Section renderers
# ---------------------------------------------------------------------------

def _render_cochange(
    scope_name: str,
    scope: dict,
    npmi_index: Dict[str, Dict[str, float]],
) -> str:
    """Render co-change contracts for a scope."""
    files = scope.get("files", [])
    if not files or not npmi_index:
        return ""

    pairs = []
    seen = set()
    for f in files:
        partners = npmi_index.get(f, {})
        for partner, npmi in partners.items():
            if npmi < 0.5:
                continue
            key = tuple(sorted([f, partner]))
            if key in seen:
                continue
            seen.add(key)
            pairs.append((key[0], key[1], npmi))

    if not pairs:
        return ""

    # Sort: NPMI descending, then File A alphabetically
    pairs.sort(key=lambda x: (-x[2], x[0]))

    lines = ["### Co-Change Contracts\n"]
    for fa, fb, npmi in pairs:
        lines.append(f"- `{os.path.basename(fa)}` <-> `{os.path.basename(fb)}` (NPMI: {npmi:.2f})")

    return "\n".join(lines) + "\n"


def _render_boundaries(
    scope_name: str,
    scopes: dict,
    scope_imports: Dict[str, Dict[str, int]],
) -> str:
    """Render boundary contracts (absent cross-scope imports)."""
    other_scopes = sorted(s for s in scopes if s != scope_name)
    if not other_scopes:
        return ""

    absent = []
    for target in other_scopes:
        count = scope_imports.get(scope_name, {}).get(target, 0)
        if count == 0:
            absent.append(target)

    if not absent:
        return ""

    lines = ["### Boundary Contracts\n"]
    for target in sorted(absent):
        lines.append(f"- No direct imports from `{target}`.")

    return "\n".join(lines) + "\n"


def _render_anti_patterns(scope: dict) -> str:
    """Render anti-patterns for a scope."""
    patterns = scope.get("anti_patterns", [])
    if not patterns:
        return ""

    # Sort by severity (GUARD > NUDGE > NOTE), then path
    severity_order = {"guard": 0, "nudge": 1, "note": 2}
    patterns.sort(key=lambda p: (
        severity_order.get(p.get("severity", "note"), 2),
        p.get("pattern", ""),
    ))

    lines = ["### Anti-Patterns\n"]
    for ap in patterns:
        pattern = ap.get("pattern", "")
        severity = ap.get("severity", "NOTE").upper()
        message = ap.get("message", pattern)
        lines.append(f"- {message}: {severity} severity.")

    return "\n".join(lines) + "\n"


def _render_conventions(scope: dict) -> str:
    """Render convention rules for a scope."""
    conventions = scope.get("conventions", [])
    if not conventions:
        return ""

    conventions.sort(key=lambda c: c.get("name", ""))

    lines = ["### Conventions\n"]
    for conv in conventions:
        name = conv.get("name", "")
        compliance = conv.get("compliance", 0)
        description = conv.get("description", "")
        rules = conv.get("rules", {})
        rule_summary = []
        if rules.get("required_methods"):
            rule_summary.append(f"requires {', '.join(rules['required_methods'])}")
        if rules.get("prohibited_imports"):
            rule_summary.append(f"prohibits importing {', '.join(rules['prohibited_imports'])}")
        if rules.get("allowed_paths"):
            rule_summary.append(f"allowed in {rules['allowed_paths'][0]}")
        detail = "; ".join(rule_summary) if rule_summary else description
        lines.append(f"- **{name}** ({compliance:.0%} compliance): {detail}")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _compute_scope_import_matrix(
    scopes: dict,
    graph_edges: Dict[str, List[str]],
) -> Dict[str, Dict[str, int]]:
    """Compute which scopes import from which other scopes.

    Returns: {source_scope: {target_scope: import_count}}
    """
    # Build file→scope mapping
    file_to_scope = {}
    for scope_name, scope_data in scopes.items():
        for f in scope_data.get("files", []):
            file_to_scope[f] = scope_name

    matrix: Dict[str, Dict[str, int]] = {}
    for source_file, targets in graph_edges.items():
        source_scope = file_to_scope.get(source_file, "")
        if not source_scope:
            continue
        if source_scope not in matrix:
            matrix[source_scope] = {}
        for target_file in targets:
            target_scope = file_to_scope.get(target_file, "")
            if target_scope and target_scope != source_scope:
                matrix[source_scope][target_scope] = matrix[source_scope].get(target_scope, 0) + 1

    return matrix


def _load_scope_data(root: str) -> dict:
    """Load scope data from .scope files."""
    try:
        from ..discovery import find_all_scopes
        from ..parser import parse_scope_file
        from ..intent import load_conventions

        scopes = {}
        for sf in find_all_scopes(root):
            try:
                config = parse_scope_file(sf)
                name = os.path.basename(os.path.dirname(config.path)) or "root"
                scopes[name] = {
                    "files": config.includes,
                    "anti_patterns": config.anti_patterns if hasattr(config, "anti_patterns") else [],
                    "context": config.context_str,
                }
            except Exception:
                continue

        # Merge conventions
        conventions = load_conventions(root)
        if conventions:
            for conv in conventions:
                # Assign convention to most relevant scope
                for scope_name in scopes:
                    if scope_name not in scopes.get(scope_name, {}).get("conventions", []):
                        if "conventions" not in scopes.get(scope_name, {}):
                            scopes[scope_name]["conventions"] = []
                        scopes[scope_name]["conventions"].append({
                            "name": conv.name,
                            "compliance": conv.compliance,
                            "description": conv.description,
                            "rules": conv.rules,
                        })
                        break  # Assign to first scope

        return scopes
    except Exception:
        return {}


def _load_graph_edges(root: str) -> Dict[str, List[str]]:
    """Load import edges from cached graph."""
    try:
        from ..storage.cache import load_cached_graph_hubs
        hubs = load_cached_graph_hubs(root)
        # Reconstruct edges from hubs (imported_by → reverse edges)
        edges: Dict[str, List[str]] = {}
        for path, hub in hubs.items():
            imported_by = hub.get("imported_by_files", [])
            if isinstance(imported_by, list):
                for importer in imported_by:
                    if importer not in edges:
                        edges[importer] = []
                    edges[importer].append(path)
        return edges
    except Exception:
        return {}


def _load_npmi_index(root: str) -> Dict[str, Dict[str, float]]:
    """Load NPMI co-change index."""
    path = Path(root) / ".dotscope" / "cache" / "npmi_index.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
