"""NETWORK_MAP.md renderer.

Renders the cross-language network topology: provider endpoints,
consumer bindings, unmatched consumers, and multi-hop flow chains.
Flow chains computed via BFS with cycle detection.
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Optional, Set

from .models import GenerateConfig, GeneratedArtifact


def render_network_map(
    root: str,
    config: GenerateConfig,
    timestamp: str,
    commit: str,
) -> GeneratedArtifact:
    """Render NETWORK_MAP.md."""
    network_edges = _load_network_edges(root)
    confidence = _load_confidence(root)
    endpoints = _load_endpoints(root)
    consumers = _load_consumers(root)

    lines = [f"# Network Map\n"]
    lines.append(f"Generated by dotscope · {timestamp} · commit {commit}\n")

    stats = {"endpoints": 0, "bindings": 0, "unmatched": 0, "flows": 0}

    # Provider Endpoints table
    endpoint_list = _build_endpoint_list(endpoints, network_edges)
    if endpoint_list:
        lines.append("\n## Provider Endpoints\n")
        lines.append("| Endpoint | Method | Handler | Consumers |")
        lines.append("|----------|--------|---------|-----------|")
        # Sort by consumer count descending, then path
        endpoint_list.sort(key=lambda e: (-e["consumers"], e["path"]))
        for ep in endpoint_list:
            lines.append(
                f"| `{ep['path']}` | {ep['method']} | "
                f"`{ep['handler']}` | {ep['consumers']} |"
            )
            stats["endpoints"] += 1

    # Consumer Bindings table
    bindings = _build_bindings(network_edges, confidence)
    if bindings:
        lines.append("\n## Consumer Bindings\n")
        lines.append("| Consumer | Provider | Confidence | Type |")
        lines.append("|----------|----------|------------|------|")
        # Sort by confidence descending, then consumer path
        bindings.sort(key=lambda b: (-b["confidence"], b["consumer"]))
        for b in bindings:
            conf_type = _confidence_label(b["confidence"])
            lines.append(
                f"| `{b['consumer']}` → `{b['method']} {b['path']}` | "
                f"`{b['handler']}` | {b['confidence']:.1f} | {conf_type} |"
            )
            stats["bindings"] += 1

    # Unmatched Consumers
    all_matched = {b["consumer"] for b in bindings}
    unmatched = []
    for path, consumer_list in consumers.items():
        for cons in consumer_list:
            consumer_key = f"{path}"
            if consumer_key not in all_matched:
                unmatched.append({
                    "consumer": consumer_key,
                    "raw_path": cons.get("raw_path", ""),
                    "method": cons.get("method", "GET"),
                })

    if unmatched:
        lines.append("\n## Unmatched Consumers\n")
        lines.append("| Consumer | Raw Path | Reason |")
        lines.append("|----------|----------|--------|")
        unmatched.sort(key=lambda u: u["consumer"])
        for u in unmatched:
            lines.append(
                f"| `{u['consumer']}` | `{u['method']} {u['raw_path']}` | "
                f"No provider matched above 0.5 confidence |"
            )
            stats["unmatched"] += 1

    # Flow Chains (3+ hops only)
    chains = _compute_flow_chains(network_edges, endpoints)
    long_chains = [c for c in chains if len(c) >= 3]
    if long_chains:
        lines.append("\n## Request Flows\n")
        # Sort by depth descending, then entry path
        long_chains.sort(key=lambda c: (-len(c), c[0].get("path", "")))
        for chain in long_chains:
            lines.append("```")
            for i, hop in enumerate(chain):
                indent = "  " * i
                handler = hop.get("handler", "")
                path = hop.get("path", "")
                conf = hop.get("confidence", 0)
                if hop.get("cycle"):
                    lines.append(f"{indent}→ [cycle → {handler}]")
                elif i == 0:
                    lines.append(f"[{hop.get('consumer', '')}] → {hop.get('method', '')} {path}")
                else:
                    conf_str = f", confidence {conf:.1f}" if conf else ""
                    lines.append(f"{indent}→ {handler} ({hop.get('file', '')})")
            lines.append("```\n")
            stats["flows"] += 1

    content = "\n".join(lines)

    return GeneratedArtifact(
        name="network_map",
        content=content,
        file_name="NETWORK_MAP.md",
        data_sources=["network_edges.json", "network_confidence.json"],
        stats=stats,
    )


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def _build_endpoint_list(
    endpoints: Dict[str, list],
    network_edges: Dict[str, Dict[str, list]],
) -> list:
    """Build a flat list of endpoints with consumer counts."""
    result = []
    seen_handlers = set()

    for file_path, ep_list in sorted(endpoints.items()):
        for ep in ep_list:
            handler = ep.get("handler", "")
            if handler in seen_handlers:
                continue
            seen_handlers.add(handler)

            consumer_count = len(network_edges.get(file_path, {}))
            result.append({
                "path": ep.get("path", ""),
                "method": ep.get("method", "ALL"),
                "handler": f"{file_path}:{handler}" if file_path else handler,
                "consumers": consumer_count,
            })

    return result


def _build_bindings(
    network_edges: Dict[str, Dict[str, list]],
    confidence: Dict,
) -> list:
    """Build consumer→provider binding list with confidence."""
    bindings = []

    for provider, consumers in sorted(network_edges.items()):
        for consumer, ep_list in sorted(consumers.items()):
            for ep in ep_list:
                # Look up confidence
                conf_key = f"{provider}|{consumer}"
                conf = confidence.get(conf_key, 1.0)
                if isinstance(conf, dict):
                    conf = 1.0

                handler = ep.get("handler", "") if isinstance(ep, dict) else getattr(ep, "handler_name", "")
                path = ep.get("path", "") if isinstance(ep, dict) else getattr(ep, "raw_path", "")
                method = ep.get("method", "") if isinstance(ep, dict) else getattr(ep, "method", "")

                bindings.append({
                    "consumer": consumer,
                    "provider": provider,
                    "handler": handler,
                    "path": path,
                    "method": method,
                    "confidence": float(conf),
                })

    return bindings


def _compute_flow_chains(
    network_edges: Dict[str, Dict[str, list]],
    endpoints: Dict[str, list],
) -> list:
    """Compute multi-hop request paths via BFS with cycle detection."""
    # Build handler→file mapping
    handler_to_file = {}
    for file_path, ep_list in endpoints.items():
        for ep in ep_list:
            handler = ep.get("handler", "")
            if handler:
                handler_to_file[handler] = file_path

    chains = []

    for provider_file, consumers in network_edges.items():
        for consumer_file, ep_list in consumers.items():
            for ep in ep_list:
                handler = ep.get("handler", "") if isinstance(ep, dict) else ""
                if not handler:
                    continue

                # BFS from this handler
                chain = [{"consumer": consumer_file, "method": ep.get("method", ""), "path": ep.get("path", ""), "handler": handler, "file": provider_file}]
                visited: Set[str] = {handler}

                current_file = provider_file
                while True:
                    # Check if current_file has outgoing network edges
                    next_hops = network_edges.get(current_file, {})
                    found_next = False
                    for next_consumer, next_eps in sorted(next_hops.items()):
                        for next_ep in next_eps:
                            next_handler = next_ep.get("handler", "") if isinstance(next_ep, dict) else ""
                            if not next_handler:
                                continue
                            if next_handler in visited:
                                chain.append({"handler": next_handler, "cycle": True})
                                found_next = False
                                break
                            visited.add(next_handler)
                            next_file = handler_to_file.get(next_handler, next_consumer)
                            chain.append({"handler": next_handler, "file": next_file, "path": next_ep.get("path", "")})
                            current_file = next_file
                            found_next = True
                            break
                        if found_next or chain[-1].get("cycle"):
                            break

                    if not found_next:
                        break

                if len(chain) >= 2:
                    chains.append(chain)

    return chains


def _confidence_label(conf: float) -> str:
    if conf >= 1.0:
        return "exact"
    elif conf >= 0.8:
        return "suffix"
    else:
        return "semantic"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _load_network_edges(root: str) -> dict:
    try:
        from ..storage.cache import load_cached_network_edges
        return load_cached_network_edges(root)
    except Exception:
        return {}


def _load_confidence(root: str) -> dict:
    path = Path(root) / ".dotscope" / "cache" / "network_confidence.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _load_endpoints(root: str) -> dict:
    """Load endpoint registry (provider endpoints per file)."""
    # Endpoints are stored as part of the graph APIs during ingest
    # For now, reconstruct from network_edges keys
    return {}


def _load_consumers(root: str) -> dict:
    """Load consumer registry (HTTP calls per file)."""
    return {}
