"""Response models for the Dotscope Pro API.

These are plain @dataclass types (matching the rest of the codebase — see
dotscope/models/core.py). Each model exposes a ``from_dict`` classmethod that
tolerates missing or unexpected keys so a partial / malformed Pro response
still parses into a safe default instance.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List


def _as_float(value: Any, default: float = 0.0) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _as_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _as_str(value: Any, default: str = "") -> str:
    return value if isinstance(value, str) else default


@dataclass
class StructuralAnalog:
    """A repo from the Genesis dataset with similar topology."""

    repo_domain: str
    similarity_score: float
    node_count: int
    edge_count: int
    insight: str

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "StructuralAnalog":
        d = d or {}
        return cls(
            repo_domain=_as_str(d.get("repo_domain"), "unknown"),
            similarity_score=_as_float(d.get("similarity_score")),
            node_count=_as_int(d.get("node_count")),
            edge_count=_as_int(d.get("edge_count")),
            insight=_as_str(d.get("insight")),
        )


@dataclass
class Directive:
    """Architectural directive generated by Pro based on topology comparison."""

    directive_type: str
    target: str
    reasoning: str
    severity: str
    confidence: float

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "Directive":
        d = d or {}
        return cls(
            directive_type=_as_str(d.get("directive_type"), "info"),
            target=_as_str(d.get("target")),
            reasoning=_as_str(d.get("reasoning")),
            severity=_as_str(d.get("severity"), "info"),
            confidence=_as_float(d.get("confidence")),
        )


@dataclass
class StructuralReport:
    """Result of comparing local topology against the Genesis swarm."""

    analog_count: int = 0
    analogs: List[StructuralAnalog] = field(default_factory=list)
    anomalies: List[str] = field(default_factory=list)
    directives: List[Directive] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "StructuralReport":
        d = d or {}
        analogs_raw = d.get("analogs") or []
        directives_raw = d.get("directives") or []
        anomalies_raw = d.get("anomalies") or []
        analogs = [StructuralAnalog.from_dict(a) for a in analogs_raw if isinstance(a, dict)]
        directives = [Directive.from_dict(x) for x in directives_raw if isinstance(x, dict)]
        anomalies = [s for s in anomalies_raw if isinstance(s, str)]
        return cls(
            analog_count=_as_int(d.get("analog_count"), default=len(analogs)),
            analogs=analogs,
            anomalies=anomalies,
            directives=directives,
        )


@dataclass
class FailureDensity:
    """Historical failure correlation for a given file shape."""

    density: float = 0.0
    severity: str = "unknown"
    matched_repos: int = 0
    explanation: str = ""

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "FailureDensity":
        d = d or {}
        return cls(
            density=_as_float(d.get("density")),
            severity=_as_str(d.get("severity"), "unknown"),
            matched_repos=_as_int(d.get("matched_repos")),
            explanation=_as_str(d.get("explanation")),
        )


@dataclass
class GlobalBaseline:
    """Global NPMI statistics aggregated across the Genesis swarm."""

    mean_max_npmi: float = 0.0
    p50_max_npmi: float = 0.0
    p90_max_npmi: float = 0.0
    repo_count: int = 0

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "GlobalBaseline":
        d = d or {}
        return cls(
            mean_max_npmi=_as_float(d.get("mean_max_npmi")),
            p50_max_npmi=_as_float(d.get("p50_max_npmi")),
            p90_max_npmi=_as_float(d.get("p90_max_npmi")),
            repo_count=_as_int(d.get("repo_count")),
        )
